export const SET_USER = 'SET_USER';
export const SET_AUTH_ME = 'SET_AUTH_ME';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_USER_NAME = 'SET_AUTH_USER_NAME';

export const SET_ALL_EVENTS = 'SET_ALL_EVENTS';
export const ADD_EVENT = 'ADD_EVENT';
export const SET_EVENT_ERROR = 'SET_EVENT_ERROR';
export const SET_EVENT_FOR_EDIT = 'SET_EVENT_FOR_EDIT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const FETCH_EVENT_IMAGES = 'FETCH_EVENT_IMAGES';
export const EVENT_IMAGE_UPLOAD = 'EVENT_IMAGE_UPLOAD';
export const EVENT_IMAGE_UPLOAD_UPDATE = 'EVENT_IMAGE_UPLOAD_UPDATE';
export const EVENT_IMAGE_DELETE_STATUS = 'EVENT_DELETE_IMAGE_STATUS';
export const EVENT_IMAGE_DELETE = 'EVENT_IMAGE_DELETE';

export const SET_ALL_USERS = 'SET_ALL_USER';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_USER_ERROR = 'SET_USER_ERROR';
